name: Singapore Lottery Automation

on:
  schedule:
    # Singapore â€” 12:31, 16:31, 20:30 IST
    - cron: "1 7 * * *"
    - cron: "1 11 * * *"
    - cron: "0 15 * * *"

  workflow_dispatch:

jobs:
  run-singapore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_singapore.txt

      - name: Run Singapore Crawler
        run: python singapore_crawler.py
